image: maven:3.9-eclipse-temurin-21

clone:
  enabled: false # we clone manually because the depth parameter is ignored for scheduled builds

definitions:
  script: &resolve-dependencies
    GIT_LFS_SKIP_SMUDGE=1 git clone --depth 1 https://x-token-auth:$REPOSITORY_OAUTH_ACCESS_TOKEN@bitbucket.org/$BITBUCKET_REPO_FULL_NAME.git $BITBUCKET_CLONE_DIR;
    cd $BITBUCKET_CLONE_DIR;
    git reset --hard $BITBUCKET_COMMIT;
    chmod 777 $BITBUCKET_CLONE_DIR;
    mvn -f commons/pom.xml install -Dmaven.source.skip=true

pipelines:
  custom: # triggered manually
    quick-build-check: # just makes sure that the project compiles
      - step:
          caches:
            - maven
          script:
            - *resolve-dependencies
            - mvn -f chat-server/pom.xml compile
            - mvn -f login-server/pom.xml compile
            - mvn -f game-server/pom.xml compile
    build-chat-server:
      - step:
          caches:
            - maven
          script:
            - *resolve-dependencies
            - mvn -f chat-server/pom.xml package -Dftp.url=$LIVESERVER_FTP_URL
    build-game-server:
      - step:
          deployment: production
          caches:
            - maven
          script:
            - *resolve-dependencies
            - mvn -f game-server/pom.xml package -Dftp.url=$LIVESERVER_FTP_URL
    build-login-server:
      - step:
          caches:
            - maven
          script:
            - *resolve-dependencies
            - mvn -f login-server/pom.xml package -Dftp.url=$LIVESERVER_FTP_URL