image: maven:3.3.9

pipelines:
  custom: # Pipelines that are triggered manually
    build-chat-server:
      - step:
          script:
            - mvn -f commons/pom.xml clean install
            - mvn -f chat-server/pom.xml clean package
    build-game-server:
      - step:
          script:
            - mvn -f commons/pom.xml clean install
            - mvn -f game-server/pom.xml clean package
    build-login-server:
      - step:
          script:
            - mvn -f commons/pom.xml clean install
            - mvn -f login-server/pom.xml clean package
  default: # default action on commit
    - step:
        script:
          - mvn --version
          - mvn -f commons/pom.xml clean install
          - mvn -f chat-server/pom.xml clean compile
          - mvn -f login-server/pom.xml clean compile
          - mvn -f game-server/pom.xml clean compile