image: maven:3.3.9

pipelines:
  custom: # Pipelines that are triggered manually
    build-chat-server:
      - step:
          script:
            - mvn -f commons/pom.xml install
            - mvn -f chat-server/pom.xml package -Dftp.url=$LIVESERVER_FTP_URL
    build-game-server:
      - step:
          script:
            - mvn -f commons/pom.xml install
            - mvn -f game-server/pom.xml package -Dftp.url=$LIVESERVER_FTP_URL
    build-login-server:
      - step:
          script:
            - mvn -f commons/pom.xml install
            - mvn -f login-server/pom.xml package -Dftp.url=$LIVESERVER_FTP_URL
  default: # default action on commit
    - step:
        script:
          - mvn -f commons/pom.xml install
          - mvn -f chat-server/pom.xml compile
          - mvn -f login-server/pom.xml compile
          - mvn -f game-server/pom.xml compile