image: maven:3.6.3

clone:
  depth: 1 # shallow git clone, since we don't need all the history

pipelines:
  custom: # triggered manually
    quick-build-check: # just makes sure that the project compiles
      - step:
          caches:
            - maven
          script:
            - mvn -f commons/pom.xml install
      - parallel:
          - step:
              script:
                - mvn -f chat-server/pom.xml compile
          - step:
              script:
                - mvn -f login-server/pom.xml compile
          - step:
              script:
                - mvn -f game-server/pom.xml compile
    build-chat-server:
      - step:
          caches:
            - maven
          script:
            - mvn -f commons/pom.xml install
            - mvn -f chat-server/pom.xml package -Dftp.url=$LIVESERVER_FTP_URL
    build-game-server:
      - step:
          deployment: production
          caches:
            - maven
          script:
            - mvn -f commons/pom.xml install
            - mvn -f game-server/pom.xml package -Dftp.url=$LIVESERVER_FTP_URL
    build-login-server:
      - step:
          caches:
            - maven
          script:
            - mvn -f commons/pom.xml install
            - mvn -f login-server/pom.xml package -Dftp.url=$LIVESERVER_FTP_URL